name: 'Build Ionic React'
description: 'Build Ionic React'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: 🕸️ Install React Dependencies
      run: npm ci
      shell: bash
      working-directory: ./packages/react
    - name: 🔄 Sync
      run: npm run sync
      shell: bash
      working-directory: ./packages/react
    - name: 🖌️ Lint
      run: npm run lint
      shell: bash
      working-directory: ./packages/react
    - name: 🏗️ Build
      run: npm run build
      shell: bash
      working-directory: ./packages/react
    - name: 🧪 Test Spec
      run: npm run test.spec
      shell: bash
      working-directory: ./packages/react
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-react
        output: packages/react/ReactBuild.zip
        paths: packages/react/dist packages/react/css packages/react/package.json
    - name: Clean package.json updates
      run: git checkout ./core/package.json ./packages/react/package.json
      shell: bash
    - name: 🔍 Check Diff
      run: git diff --exit-code
      shell: bash
