/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
