/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import41 from '@angular/core/src/di/injector';
import * as import78 from '@angular/core/src/linker/view';
import * as import79 from '@angular/core/src/linker/element';
import * as import80 from '@angular/core/src/linker/view_utils';
import * as import83 from '@angular/core/src/linker/component_factory';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
export declare const E2EPageNgFactory: import83.ComponentFactory<import1.E2EPage>;
export declare function viewFactory_E2EPage0(viewUtils: import80.ViewUtils, parentInjector: import41.Injector, declarationEl: import79.AppElement): import78.AppView<import1.E2EPage>;
export declare const E2EAppNgFactory: import83.ComponentFactory<import1.E2EApp>;
export declare function viewFactory_E2EApp0(viewUtils: import80.ViewUtils, parentInjector: import41.Injector, declarationEl: import79.AppElement): import78.AppView<import1.E2EApp>;
