/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import40 from '@angular/core/src/di/injector';
import * as import77 from '@angular/core/src/linker/view';
import * as import78 from '@angular/core/src/linker/element';
import * as import79 from '@angular/core/src/linker/view_utils';
import * as import82 from '@angular/core/src/linker/component_factory';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
export declare const MyCmpTestNgFactory: import82.ComponentFactory<import1.MyCmpTest>;
export declare function viewFactory_MyCmpTest0(viewUtils: import79.ViewUtils, parentInjector: import40.Injector, declarationEl: import78.AppElement): import77.AppView<import1.MyCmpTest>;
export declare const FirstPageNgFactory: import82.ComponentFactory<import1.FirstPage>;
export declare function viewFactory_FirstPage0(viewUtils: import79.ViewUtils, parentInjector: import40.Injector, declarationEl: import78.AppElement): import77.AppView<import1.FirstPage>;
export declare const FullPageNgFactory: import82.ComponentFactory<import1.FullPage>;
export declare function viewFactory_FullPage0(viewUtils: import79.ViewUtils, parentInjector: import40.Injector, declarationEl: import78.AppElement): import77.AppView<import1.FullPage>;
export declare const PrimaryHeaderPageNgFactory: import82.ComponentFactory<import1.PrimaryHeaderPage>;
export declare function viewFactory_PrimaryHeaderPage0(viewUtils: import79.ViewUtils, parentInjector: import40.Injector, declarationEl: import78.AppElement): import77.AppView<import1.PrimaryHeaderPage>;
export declare const AnotherPageNgFactory: import82.ComponentFactory<import1.AnotherPage>;
export declare function viewFactory_AnotherPage0(viewUtils: import79.ViewUtils, parentInjector: import40.Injector, declarationEl: import78.AppElement): import77.AppView<import1.AnotherPage>;
export declare const E2EAppNgFactory: import82.ComponentFactory<import1.E2EApp>;
export declare function viewFactory_E2EApp0(viewUtils: import79.ViewUtils, parentInjector: import40.Injector, declarationEl: import78.AppElement): import77.AppView<import1.E2EApp>;
