/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import2 from '@angular/common/index';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '../dist/components/app/app';
import * as import8 from '@angular/core/src/application_init';
import * as import9 from '@angular/core/src/testability/testability';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '../dist/ionic-module';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/core/src/linker/dynamic_component_loader';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/forms/src/form_builder';
import * as import22 from '../dist/components/action-sheet/action-sheet';
import * as import23 from '../dist/components/alert/alert';
import * as import24 from '../dist/util/form';
import * as import25 from '../dist/util/feature-detect';
import * as import26 from '../dist/gestures/gesture-controller';
import * as import27 from '@angular/http/src/backends/browser_xhr';
import * as import28 from '@angular/http/src/base_response_options';
import * as import29 from '@angular/http/src/backends/xhr_backend';
import * as import30 from '@angular/http/src/base_request_options';
import * as import31 from '../dist/util/keyboard';
import * as import32 from '../dist/components/loading/loading';
import * as import33 from '../dist/components/menu/menu-controller';
import * as import34 from '../dist/components/modal/modal';
import * as import35 from '../dist/components/picker/picker';
import * as import36 from '../dist/components/popover/popover';
import * as import37 from '../dist/components/tap-click/tap-click';
import * as import38 from '../dist/components/toast/toast';
import * as import39 from '../dist/translation/translate';
import * as import40 from '../dist/transitions/transition-controller';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from '../dist/components/app/app-root.d.ngfactory';
import * as import43 from '@angular/core/src/application_tokens';
import * as import44 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import45 from '@angular/platform-browser/src/dom/events/key_events';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import48 from '@angular/forms/src/directives/ng_model';
import * as import49 from '@angular/forms/src/directives/ng_model_group';
import * as import50 from '@angular/forms/src/directives/ng_form';
import * as import51 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import52 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import53 from '@angular/forms/src/directives/default_value_accessor';
import * as import54 from '@angular/forms/src/directives/number_value_accessor';
import * as import55 from '@angular/forms/src/directives/checkbox_value_accessor';
import * as import56 from '@angular/forms/src/directives/ng_control_status';
import * as import57 from '@angular/forms/src/directives/validators';
import * as import58 from '@angular/http/http';
import * as import59 from '../dist/providers';
import * as import60 from '../dist/platform/query-params';
import * as import61 from '../dist/platform/platform';
import * as import62 from '../dist/config/config';
import * as import63 from '../dist/util/events';
import * as import64 from '@angular/core/src/console';
import * as import65 from '@angular/core/src/facade/exception_handler';
import * as import66 from '@angular/core/src/linker/component_resolver';
import * as import67 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import68 from '@angular/platform-browser/src/dom/animation_driver';
import * as import69 from '@angular/core/src/render/api';
import * as import70 from '@angular/core/src/security';
import * as import71 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import72 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import73 from '../dist/components/app/app-root';
import * as import74 from '@angular/core/src/platform_directives_and_pipes';
import * as import75 from '@angular/http/src/interfaces';
import * as import76 from '@angular/http/src/http';
import * as import77 from '@angular/core/src/render/api';
import * as import78 from '@angular/core/src/linker/view';
import * as import79 from '@angular/core/src/linker/element';
import * as import80 from '@angular/core/src/linker/view_utils';
import * as import81 from '@angular/core/src/linker/view_type';
import * as import82 from '@angular/core/src/change_detection/change_detection';
import * as import83 from '@angular/core/src/linker/component_factory';
import * as import84 from '../dist/components/toolbar/toolbar';
import * as import85 from '../dist/components/toolbar/toolbar-title';
import * as import86 from '../dist/components/content/content';
import * as import87 from '../dist/components/spinner/spinner';
import * as import88 from '../dist/components/button/button';
import * as import89 from '../dist/components/nav/view-controller';
import * as import90 from '../dist/components/toolbar/toolbar.d.ngfactory';
import * as import91 from '@angular/core/src/linker/element_ref';
import * as import92 from '../dist/components/toolbar/toolbar-title.d.ngfactory';
import * as import93 from '../dist/components/navbar/navbar';
import * as import94 from '../dist/components/content/content.d.ngfactory';
import * as import95 from '../dist/components/tabs/tabs';
import * as import96 from '../dist/components/spinner/spinner.d.ngfactory';
import * as import97 from '../dist/components/button/button.d.ngfactory';
import * as import98 from '@angular/core/src/metadata/view';
import * as import99 from '../dist/components/nav/nav';
import * as import100 from '../dist/components/nav/nav.d.ngfactory';
import * as import101 from '../dist/components/nav/nav-controller-base';
import * as import102 from '@angular/core/src/linker/component_factory_resolver';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ExceptionHandler_5:any;
  _UserUrl_6:any;
  _QueryParams_7:any;
  _UserAgent_8:any;
  _UserNavigatorPlatform_9:any;
  _Platform_10:any;
  _UserConfig_11:any;
  _Config_12:any;
  _App_13:import7.App;
  _APP_INITIALIZER_14:any[];
  _ApplicationInitStatus_15:import8.ApplicationInitStatus;
  _Testability_16:import9.Testability;
  _ApplicationRef__17:import10.ApplicationRef_;
  _ApplicationRef_18:any;
  _IonicModule_19:import11.IonicModule;
  _AppModule_20:import1.AppModule;
  __Compiler_21:import12.Compiler;
  __ComponentResolver_22:any;
  __APP_ID_23:any;
  __DOCUMENT_24:any;
  __HAMMER_GESTURE_CONFIG_25:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_26:any[];
  __EventManager_27:import14.EventManager;
  __DomSharedStylesHost_28:import15.DomSharedStylesHost;
  __AnimationDriver_29:any;
  __DomRootRenderer_30:import16.DomRootRenderer_;
  __RootRenderer_31:any;
  __DomSanitizationService_32:import17.DomSanitizationServiceImpl;
  __SanitizationService_33:any;
  __ViewUtils_34:import18.ViewUtils;
  __IterableDiffers_35:any;
  __KeyValueDiffers_36:any;
  __DynamicComponentLoader_37:import19.DynamicComponentLoader_;
  __SharedStylesHost_38:any;
  __RadioControlRegistry_39:import20.RadioControlRegistry;
  __UserRoot_40:any;
  __PLATFORM_DIRECTIVES_41:any[];
  __FormBuilder_42:import21.FormBuilder;
  __ActionSheetController_43:import22.ActionSheetController;
  __AlertController_44:import23.AlertController;
  __Form_45:import24.Form;
  __FeatureDetect_46:import25.FeatureDetect;
  __GestureController_47:import26.GestureController;
  __BrowserXhr_48:import27.BrowserXhr;
  __ResponseOptions_49:import28.BaseResponseOptions;
  __XSRFStrategy_50:any;
  __XHRBackend_51:import29.XHRBackend;
  __RequestOptions_52:import30.BaseRequestOptions;
  __Http_53:any;
  __Keyboard_54:import31.Keyboard;
  __LoadingController_55:import32.LoadingController;
  __MenuController_56:import33.MenuController;
  __ModalController_57:import34.ModalController;
  __PickerController_58:import35.PickerController;
  __PopoverController_59:import36.PopoverController;
  __TapClick_60:import37.TapClick;
  __ToastController_61:import38.ToastController;
  __Translate_62:import39.Translate;
  __TransitionController_63:import40.TransitionController;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.AppRootNgFactory,
      E2EAppNgFactory,
      E2EPageNgFactory,
      E2EAppNgFactory
    ]
    ,[E2EAppNgFactory]);
  }
  get _Compiler_21():import12.Compiler {
    if ((this.__Compiler_21 == null)) { (this.__Compiler_21 = new import12.Compiler()); }
    return this.__Compiler_21;
  }
  get _ComponentResolver_22():any {
    if ((this.__ComponentResolver_22 == null)) { (this.__ComponentResolver_22 = this._Compiler_21); }
    return this.__ComponentResolver_22;
  }
  get _APP_ID_23():any {
    if ((this.__APP_ID_23 == null)) { (this.__APP_ID_23 = import43._appIdRandomProviderFactory()); }
    return this.__APP_ID_23;
  }
  get _DOCUMENT_24():any {
    if ((this.__DOCUMENT_24 == null)) { (this.__DOCUMENT_24 = import4._document()); }
    return this.__DOCUMENT_24;
  }
  get _HAMMER_GESTURE_CONFIG_25():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_25 == null)) { (this.__HAMMER_GESTURE_CONFIG_25 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_25;
  }
  get _EVENT_MANAGER_PLUGINS_26():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_26 == null)) { (this.__EVENT_MANAGER_PLUGINS_26 = [
      new import44.DomEventsPlugin(),
      new import45.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_25)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_26;
  }
  get _EventManager_27():import14.EventManager {
    if ((this.__EventManager_27 == null)) { (this.__EventManager_27 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_26,this.parent.get(import46.NgZone))); }
    return this.__EventManager_27;
  }
  get _DomSharedStylesHost_28():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_28 == null)) { (this.__DomSharedStylesHost_28 = new import15.DomSharedStylesHost(this._DOCUMENT_24)); }
    return this.__DomSharedStylesHost_28;
  }
  get _AnimationDriver_29():any {
    if ((this.__AnimationDriver_29 == null)) { (this.__AnimationDriver_29 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_29;
  }
  get _DomRootRenderer_30():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_30 == null)) { (this.__DomRootRenderer_30 = new import16.DomRootRenderer_(this._DOCUMENT_24,this._EventManager_27,this._DomSharedStylesHost_28,this._AnimationDriver_29)); }
    return this.__DomRootRenderer_30;
  }
  get _RootRenderer_31():any {
    if ((this.__RootRenderer_31 == null)) { (this.__RootRenderer_31 = import47._createConditionalRootRenderer(this._DomRootRenderer_30)); }
    return this.__RootRenderer_31;
  }
  get _DomSanitizationService_32():import17.DomSanitizationServiceImpl {
    if ((this.__DomSanitizationService_32 == null)) { (this.__DomSanitizationService_32 = new import17.DomSanitizationServiceImpl()); }
    return this.__DomSanitizationService_32;
  }
  get _SanitizationService_33():any {
    if ((this.__SanitizationService_33 == null)) { (this.__SanitizationService_33 = this._DomSanitizationService_32); }
    return this.__SanitizationService_33;
  }
  get _ViewUtils_34():import18.ViewUtils {
    if ((this.__ViewUtils_34 == null)) { (this.__ViewUtils_34 = new import18.ViewUtils(this._RootRenderer_31,this._APP_ID_23,this._SanitizationService_33)); }
    return this.__ViewUtils_34;
  }
  get _IterableDiffers_35():any {
    if ((this.__IterableDiffers_35 == null)) { (this.__IterableDiffers_35 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_35;
  }
  get _KeyValueDiffers_36():any {
    if ((this.__KeyValueDiffers_36 == null)) { (this.__KeyValueDiffers_36 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_36;
  }
  get _DynamicComponentLoader_37():import19.DynamicComponentLoader_ {
    if ((this.__DynamicComponentLoader_37 == null)) { (this.__DynamicComponentLoader_37 = new import19.DynamicComponentLoader_(this._Compiler_21)); }
    return this.__DynamicComponentLoader_37;
  }
  get _SharedStylesHost_38():any {
    if ((this.__SharedStylesHost_38 == null)) { (this.__SharedStylesHost_38 = this._DomSharedStylesHost_28); }
    return this.__SharedStylesHost_38;
  }
  get _RadioControlRegistry_39():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_39 == null)) { (this.__RadioControlRegistry_39 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_39;
  }
  get _UserRoot_40():any {
    if ((this.__UserRoot_40 == null)) { (this.__UserRoot_40 = import1.E2EApp); }
    return this.__UserRoot_40;
  }
  get _PLATFORM_DIRECTIVES_41():any[] {
      if ((this.__PLATFORM_DIRECTIVES_41 == null)) { (this.__PLATFORM_DIRECTIVES_41 = [[
        [
          import48.NgModel,
          import49.NgModelGroup,
          import50.NgForm
        ]
        ,
        [
          import51.NgSelectOption,
          import52.NgSelectMultipleOption,
          import53.DefaultValueAccessor,
          import54.NumberValueAccessor,
          import55.CheckboxControlValueAccessor,
          import51.SelectControlValueAccessor,
          import52.SelectMultipleControlValueAccessor,
          import20.RadioControlValueAccessor,
          import56.NgControlStatus,
          import57.RequiredValidator,
          import57.MinLengthValidator,
          import57.MaxLengthValidator,
          import57.PatternValidator
        ]

      ]
    ]); }
    return this.__PLATFORM_DIRECTIVES_41;
  }
  get _FormBuilder_42():import21.FormBuilder {
    if ((this.__FormBuilder_42 == null)) { (this.__FormBuilder_42 = new import21.FormBuilder()); }
    return this.__FormBuilder_42;
  }
  get _ActionSheetController_43():import22.ActionSheetController {
    if ((this.__ActionSheetController_43 == null)) { (this.__ActionSheetController_43 = new import22.ActionSheetController(this._App_13)); }
    return this.__ActionSheetController_43;
  }
  get _AlertController_44():import23.AlertController {
    if ((this.__AlertController_44 == null)) { (this.__AlertController_44 = new import23.AlertController(this._App_13)); }
    return this.__AlertController_44;
  }
  get _Form_45():import24.Form {
    if ((this.__Form_45 == null)) { (this.__Form_45 = new import24.Form()); }
    return this.__Form_45;
  }
  get _FeatureDetect_46():import25.FeatureDetect {
    if ((this.__FeatureDetect_46 == null)) { (this.__FeatureDetect_46 = new import25.FeatureDetect()); }
    return this.__FeatureDetect_46;
  }
  get _GestureController_47():import26.GestureController {
    if ((this.__GestureController_47 == null)) { (this.__GestureController_47 = new import26.GestureController(this._App_13)); }
    return this.__GestureController_47;
  }
  get _BrowserXhr_48():import27.BrowserXhr {
    if ((this.__BrowserXhr_48 == null)) { (this.__BrowserXhr_48 = new import27.BrowserXhr()); }
    return this.__BrowserXhr_48;
  }
  get _ResponseOptions_49():import28.BaseResponseOptions {
    if ((this.__ResponseOptions_49 == null)) { (this.__ResponseOptions_49 = new import28.BaseResponseOptions()); }
    return this.__ResponseOptions_49;
  }
  get _XSRFStrategy_50():any {
    if ((this.__XSRFStrategy_50 == null)) { (this.__XSRFStrategy_50 = import58._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_50;
  }
  get _XHRBackend_51():import29.XHRBackend {
    if ((this.__XHRBackend_51 == null)) { (this.__XHRBackend_51 = new import29.XHRBackend(this._BrowserXhr_48,this._ResponseOptions_49,this._XSRFStrategy_50)); }
    return this.__XHRBackend_51;
  }
  get _RequestOptions_52():import30.BaseRequestOptions {
    if ((this.__RequestOptions_52 == null)) { (this.__RequestOptions_52 = new import30.BaseRequestOptions()); }
    return this.__RequestOptions_52;
  }
  get _Http_53():any {
    if ((this.__Http_53 == null)) { (this.__Http_53 = import58.httpFactory(this._XHRBackend_51,this._RequestOptions_52)); }
    return this.__Http_53;
  }
  get _Keyboard_54():import31.Keyboard {
    if ((this.__Keyboard_54 == null)) { (this.__Keyboard_54 = new import31.Keyboard(this._Config_12,this._Form_45,this.parent.get(import46.NgZone))); }
    return this.__Keyboard_54;
  }
  get _LoadingController_55():import32.LoadingController {
    if ((this.__LoadingController_55 == null)) { (this.__LoadingController_55 = new import32.LoadingController(this._App_13)); }
    return this.__LoadingController_55;
  }
  get _MenuController_56():import33.MenuController {
    if ((this.__MenuController_56 == null)) { (this.__MenuController_56 = new import33.MenuController()); }
    return this.__MenuController_56;
  }
  get _ModalController_57():import34.ModalController {
    if ((this.__ModalController_57 == null)) { (this.__ModalController_57 = new import34.ModalController(this._App_13)); }
    return this.__ModalController_57;
  }
  get _PickerController_58():import35.PickerController {
    if ((this.__PickerController_58 == null)) { (this.__PickerController_58 = new import35.PickerController(this._App_13)); }
    return this.__PickerController_58;
  }
  get _PopoverController_59():import36.PopoverController {
    if ((this.__PopoverController_59 == null)) { (this.__PopoverController_59 = new import36.PopoverController(this._App_13)); }
    return this.__PopoverController_59;
  }
  get _TapClick_60():import37.TapClick {
    if ((this.__TapClick_60 == null)) { (this.__TapClick_60 = new import37.TapClick(this._Config_12,this._App_13,this.parent.get(import46.NgZone))); }
    return this.__TapClick_60;
  }
  get _ToastController_61():import38.ToastController {
    if ((this.__ToastController_61 == null)) { (this.__ToastController_61 = new import38.ToastController(this._App_13)); }
    return this.__ToastController_61;
  }
  get _Translate_62():import39.Translate {
    if ((this.__Translate_62 == null)) { (this.__Translate_62 = new import39.Translate()); }
    return this.__Translate_62;
  }
  get _TransitionController_63():import40.TransitionController {
    if ((this.__TransitionController_63 == null)) { (this.__TransitionController_63 = new import40.TransitionController()); }
    return this.__TransitionController_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule();
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ExceptionHandler_5 = import4._exceptionHandler();
    this._UserUrl_6 = import59.getWindowLocation();
    this._QueryParams_7 = import60.setupQueryParams(this._UserUrl_6);
    this._UserAgent_8 = import59.getWindowUserAgent();
    this._UserNavigatorPlatform_9 = import59.getWindowPlatform();
    this._Platform_10 = import61.setupPlatform(this._QueryParams_7,this._UserAgent_8,this._UserNavigatorPlatform_9,this.parent.get(import46.NgZone));
    this._UserConfig_11 = null;
    this._Config_12 = import62.setupConfig(this._UserConfig_11,this._QueryParams_7,this._Platform_10);
    this._App_13 = new import7.App(this._Config_12,this._Platform_10);
    this._APP_INITIALIZER_14 = [
      import63.setupProvideEvents(this._Platform_10),
      import37.setupTapClick(this._Config_12,this._App_13,this.parent.get(import46.NgZone))
    ]
    ;
    this._ApplicationInitStatus_15 = new import8.ApplicationInitStatus(this._APP_INITIALIZER_14);
    this._Testability_16 = new import9.Testability(this.parent.get(import46.NgZone));
    this._ApplicationRef__17 = new import10.ApplicationRef_(this.parent.get(import46.NgZone),this.parent.get(import64.Console),this,this._ExceptionHandler_5,this,this._ApplicationInitStatus_15,this.parent.get(import9.TestabilityRegistry,null),this._Testability_16);
    this._ApplicationRef_18 = this._ApplicationRef__17;
    this._IonicModule_19 = new import11.IonicModule(this.parent.get(import11.IonicModule,null),this._ApplicationRef_18);
    this._AppModule_20 = new import1.AppModule();
    return this._AppModule_20;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import65.ExceptionHandler)) { return this._ExceptionHandler_5; }
    if ((token === import60.UserUrl)) { return this._UserUrl_6; }
    if ((token === import60.QueryParams)) { return this._QueryParams_7; }
    if ((token === import61.UserAgent)) { return this._UserAgent_8; }
    if ((token === import61.UserNavigatorPlatform)) { return this._UserNavigatorPlatform_9; }
    if ((token === import61.Platform)) { return this._Platform_10; }
    if ((token === import62.UserConfig)) { return this._UserConfig_11; }
    if ((token === import62.Config)) { return this._Config_12; }
    if ((token === import7.App)) { return this._App_13; }
    if ((token === import8.APP_INITIALIZER)) { return this._APP_INITIALIZER_14; }
    if ((token === import8.ApplicationInitStatus)) { return this._ApplicationInitStatus_15; }
    if ((token === import9.Testability)) { return this._Testability_16; }
    if ((token === import10.ApplicationRef_)) { return this._ApplicationRef__17; }
    if ((token === import10.ApplicationRef)) { return this._ApplicationRef_18; }
    if ((token === import11.IonicModule)) { return this._IonicModule_19; }
    if ((token === import1.AppModule)) { return this._AppModule_20; }
    if ((token === import12.Compiler)) { return this._Compiler_21; }
    if ((token === import66.ComponentResolver)) { return this._ComponentResolver_22; }
    if ((token === import43.APP_ID)) { return this._APP_ID_23; }
    if ((token === import67.DOCUMENT)) { return this._DOCUMENT_24; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_25; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_26; }
    if ((token === import14.EventManager)) { return this._EventManager_27; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_28; }
    if ((token === import68.AnimationDriver)) { return this._AnimationDriver_29; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_30; }
    if ((token === import69.RootRenderer)) { return this._RootRenderer_31; }
    if ((token === import17.DomSanitizationService)) { return this._DomSanitizationService_32; }
    if ((token === import70.SanitizationService)) { return this._SanitizationService_33; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_34; }
    if ((token === import71.IterableDiffers)) { return this._IterableDiffers_35; }
    if ((token === import72.KeyValueDiffers)) { return this._KeyValueDiffers_36; }
    if ((token === import19.DynamicComponentLoader)) { return this._DynamicComponentLoader_37; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_38; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_39; }
    if ((token === import73.UserRoot)) { return this._UserRoot_40; }
    if ((token === import74.PLATFORM_DIRECTIVES)) { return this._PLATFORM_DIRECTIVES_41; }
    if ((token === import21.FormBuilder)) { return this._FormBuilder_42; }
    if ((token === import22.ActionSheetController)) { return this._ActionSheetController_43; }
    if ((token === import23.AlertController)) { return this._AlertController_44; }
    if ((token === import24.Form)) { return this._Form_45; }
    if ((token === import25.FeatureDetect)) { return this._FeatureDetect_46; }
    if ((token === import26.GestureController)) { return this._GestureController_47; }
    if ((token === import27.BrowserXhr)) { return this._BrowserXhr_48; }
    if ((token === import28.ResponseOptions)) { return this._ResponseOptions_49; }
    if ((token === import75.XSRFStrategy)) { return this._XSRFStrategy_50; }
    if ((token === import29.XHRBackend)) { return this._XHRBackend_51; }
    if ((token === import30.RequestOptions)) { return this._RequestOptions_52; }
    if ((token === import76.Http)) { return this._Http_53; }
    if ((token === import31.Keyboard)) { return this._Keyboard_54; }
    if ((token === import32.LoadingController)) { return this._LoadingController_55; }
    if ((token === import33.MenuController)) { return this._MenuController_56; }
    if ((token === import34.ModalController)) { return this._ModalController_57; }
    if ((token === import35.PickerController)) { return this._PickerController_58; }
    if ((token === import36.PopoverController)) { return this._PopoverController_59; }
    if ((token === import37.TapClick)) { return this._TapClick_60; }
    if ((token === import38.ToastController)) { return this._ToastController_61; }
    if ((token === import39.Translate)) { return this._Translate_62; }
    if ((token === import40.TransitionController)) { return this._TransitionController_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__17.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);
var renderType_E2EPage_Host:import77.RenderComponentType = null;
class _View_E2EPage_Host0 extends import78.AppView<any> {
  _el_0:any;
  private _appEl_0:import79.AppElement;
  _E2EPage_0_4:import1.E2EPage;
  constructor(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement) {
    super(_View_E2EPage_Host0,renderType_E2EPage_Host,import81.ViewType.HOST,viewUtils,parentInjector,declarationEl,import82.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import79.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import79.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EPage_0_4 = new import1.E2EPage();
    this._appEl_0.initComponent(this._E2EPage_0_4,[],compView_0);
    compView_0.create(this._E2EPage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EPage) && (0 === requestNodeIndex))) { return this._E2EPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EPage_Host0(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement):import78.AppView<any> {
  if ((renderType_E2EPage_Host === null)) { (renderType_E2EPage_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EPageNgFactory:import83.ComponentFactory<import1.E2EPage> = new import83.ComponentFactory<import1.E2EPage>('ng-component',viewFactory_E2EPage_Host0,import1.E2EPage);
const styles_E2EPage:any[] = [];
var renderType_E2EPage:import77.RenderComponentType = null;
class _View_E2EPage0 extends import78.AppView<import1.E2EPage> {
  _el_0:any;
  _Header_0_3:import84.Header;
  _text_1:any;
  _el_2:any;
  private _appEl_2:import79.AppElement;
  _Toolbar_2_4:import84.Toolbar;
  _text_3:any;
  _el_4:any;
  private _appEl_4:import79.AppElement;
  _ToolbarTitle_4_4:import85.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  private _appEl_9:import79.AppElement;
  _Content_9_4:import86.Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  private _appEl_21:import79.AppElement;
  _Spinner_21_4:import87.Spinner;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  private _appEl_32:import79.AppElement;
  _Spinner_32_4:import87.Spinner;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  private _appEl_43:import79.AppElement;
  _Spinner_43_4:import87.Spinner;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  private _appEl_54:import79.AppElement;
  _Spinner_54_4:import87.Spinner;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  private _appEl_65:import79.AppElement;
  _Spinner_65_4:import87.Spinner;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  private _appEl_76:import79.AppElement;
  _Spinner_76_4:import87.Spinner;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  private _appEl_87:import79.AppElement;
  _Spinner_87_4:import87.Spinner;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  private _appEl_92:import79.AppElement;
  _Button_92_4:import88.Button;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  private _expr_0:any;
  private _expr_1:any;
  private _expr_2:any;
  private _expr_3:any;
  private _expr_4:any;
  private _expr_5:any;
  private _expr_6:any;
  private _expr_7:any;
  private _expr_8:any;
  private _expr_9:any;
  private _expr_10:any;
  private _expr_11:any;
  private _expr_12:any;
  private _expr_13:any;
  private _expr_14:any;
  private _expr_15:any;
  private _expr_16:any;
  private _expr_17:any;
  private _expr_18:any;
  private _expr_19:any;
  private _expr_20:any;
  private _expr_21:any;
  private _expr_22:any;
  private _expr_23:any;
  private _expr_24:any;
  private _expr_25:any;
  private _expr_26:any;
  private _expr_27:any;
  private _expr_28:any;
  private _expr_29:any;
  private _expr_30:any;
  constructor(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement) {
    super(_View_E2EPage0,renderType_E2EPage,import81.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import82.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import79.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',null);
    this._Header_0_3 = new import84.Header(this.parentInjector.get(import89.ViewController,null));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',null);
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',null);
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import79.AppElement(2,0,this,this._el_2);
    var compView_2:any = import90.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import84.Toolbar(this.parentInjector.get(import89.ViewController,null),this._Header_0_3,this.parentInjector.get(import84.Footer,null),this.parentInjector.get(import62.Config),new import91.ElementRef(this._el_2));
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText(null,'\n    ',null);
    this._el_4 = this.renderer.createElement(null,'ion-title',null);
    this._appEl_4 = new import79.AppElement(4,2,this,this._el_4);
    var compView_4:any = import92.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import85.ToolbarTitle(new import91.ElementRef(this._el_4),this._Toolbar_2_4,this.parentInjector.get(import93.Navbar,null));
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText(null,'Spinners',null);
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],null);
    this._text_6 = this.renderer.createText(null,'\n  ',null);
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,null);
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',null);
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',null);
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',null);
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import79.AppElement(9,null,this,this._el_9);
    var compView_9:any = import94.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import86.Content(new import91.ElementRef(this._el_9),this.parentInjector.get(import62.Config),this.parentInjector.get(import7.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import46.NgZone),this.parentInjector.get(import89.ViewController,null),this.parentInjector.get(import95.Tabs,null));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText(null,'\n\n  ',null);
    this._el_11 = this.renderer.createElement(null,'table',null);
    this.renderer.setElementAttribute(this._el_11,'style','border-collapse:initial; border-spacing: 20px');
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',null);
    this._el_13 = this.renderer.createElement(this._el_11,'tbody',null);
    this._el_14 = this.renderer.createElement(this._el_13,'tr',null);
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',null);
    this._el_16 = this.renderer.createElement(this._el_14,'td',null);
    this._text_17 = this.renderer.createText(this._el_16,'Platform Default',null);
    this._text_18 = this.renderer.createText(this._el_14,'\n      ',null);
    this._el_19 = this.renderer.createElement(this._el_14,'td',null);
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',null);
    this._el_21 = this.renderer.createElement(this._el_19,'ion-spinner',null);
    this._appEl_21 = new import79.AppElement(21,19,this,this._el_21);
    var compView_21:any = import96.viewFactory_Spinner0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Spinner_21_4 = new import87.Spinner(this.parentInjector.get(import62.Config));
    this._appEl_21.initComponent(this._Spinner_21_4,[],compView_21);
    compView_21.create(this._Spinner_21_4,[],null);
    this._text_22 = this.renderer.createText(this._el_19,'\n      ',null);
    this._text_23 = this.renderer.createText(this._el_14,'\n    ',null);
    this._text_24 = this.renderer.createText(this._el_13,'\n    ',null);
    this._el_25 = this.renderer.createElement(this._el_13,'tr',null);
    this._text_26 = this.renderer.createText(this._el_25,'\n      ',null);
    this._el_27 = this.renderer.createElement(this._el_25,'td',null);
    this._text_28 = this.renderer.createText(this._el_27,'ios',null);
    this._text_29 = this.renderer.createText(this._el_25,'\n      ',null);
    this._el_30 = this.renderer.createElement(this._el_25,'td',null);
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',null);
    this._el_32 = this.renderer.createElement(this._el_30,'ion-spinner',null);
    this.renderer.setElementAttribute(this._el_32,'duration','1000');
    this.renderer.setElementAttribute(this._el_32,'name','ios');
    this._appEl_32 = new import79.AppElement(32,30,this,this._el_32);
    var compView_32:any = import96.viewFactory_Spinner0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Spinner_32_4 = new import87.Spinner(this.parentInjector.get(import62.Config));
    this._appEl_32.initComponent(this._Spinner_32_4,[],compView_32);
    compView_32.create(this._Spinner_32_4,[],null);
    this._text_33 = this.renderer.createText(this._el_30,'\n      ',null);
    this._text_34 = this.renderer.createText(this._el_25,'\n    ',null);
    this._text_35 = this.renderer.createText(this._el_13,'\n    ',null);
    this._el_36 = this.renderer.createElement(this._el_13,'tr',null);
    this._text_37 = this.renderer.createText(this._el_36,'\n      ',null);
    this._el_38 = this.renderer.createElement(this._el_36,'td',null);
    this._text_39 = this.renderer.createText(this._el_38,'ios-small',null);
    this._text_40 = this.renderer.createText(this._el_36,'\n      ',null);
    this._el_41 = this.renderer.createElement(this._el_36,'td',null);
    this._text_42 = this.renderer.createText(this._el_41,'\n        ',null);
    this._el_43 = this.renderer.createElement(this._el_41,'ion-spinner',null);
    this.renderer.setElementAttribute(this._el_43,'duration','1000');
    this.renderer.setElementAttribute(this._el_43,'name','ios-small');
    this._appEl_43 = new import79.AppElement(43,41,this,this._el_43);
    var compView_43:any = import96.viewFactory_Spinner0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Spinner_43_4 = new import87.Spinner(this.parentInjector.get(import62.Config));
    this._appEl_43.initComponent(this._Spinner_43_4,[],compView_43);
    compView_43.create(this._Spinner_43_4,[],null);
    this._text_44 = this.renderer.createText(this._el_41,'\n      ',null);
    this._text_45 = this.renderer.createText(this._el_36,'\n    ',null);
    this._text_46 = this.renderer.createText(this._el_13,'\n    ',null);
    this._el_47 = this.renderer.createElement(this._el_13,'tr',null);
    this._text_48 = this.renderer.createText(this._el_47,'\n      ',null);
    this._el_49 = this.renderer.createElement(this._el_47,'td',null);
    this._text_50 = this.renderer.createText(this._el_49,'bubbles',null);
    this._text_51 = this.renderer.createText(this._el_47,'\n      ',null);
    this._el_52 = this.renderer.createElement(this._el_47,'td',null);
    this._text_53 = this.renderer.createText(this._el_52,'\n        ',null);
    this._el_54 = this.renderer.createElement(this._el_52,'ion-spinner',null);
    this.renderer.setElementAttribute(this._el_54,'name','bubbles');
    this._appEl_54 = new import79.AppElement(54,52,this,this._el_54);
    var compView_54:any = import96.viewFactory_Spinner0(this.viewUtils,this.injector(54),this._appEl_54);
    this._Spinner_54_4 = new import87.Spinner(this.parentInjector.get(import62.Config));
    this._appEl_54.initComponent(this._Spinner_54_4,[],compView_54);
    compView_54.create(this._Spinner_54_4,[],null);
    this._text_55 = this.renderer.createText(this._el_52,'\n      ',null);
    this._text_56 = this.renderer.createText(this._el_47,'\n    ',null);
    this._text_57 = this.renderer.createText(this._el_13,'\n    ',null);
    this._el_58 = this.renderer.createElement(this._el_13,'tr',null);
    this._text_59 = this.renderer.createText(this._el_58,'\n      ',null);
    this._el_60 = this.renderer.createElement(this._el_58,'td',null);
    this._text_61 = this.renderer.createText(this._el_60,'circles',null);
    this._text_62 = this.renderer.createText(this._el_58,'\n      ',null);
    this._el_63 = this.renderer.createElement(this._el_58,'td',null);
    this._text_64 = this.renderer.createText(this._el_63,'\n        ',null);
    this._el_65 = this.renderer.createElement(this._el_63,'ion-spinner',null);
    this.renderer.setElementAttribute(this._el_65,'name','circles');
    this._appEl_65 = new import79.AppElement(65,63,this,this._el_65);
    var compView_65:any = import96.viewFactory_Spinner0(this.viewUtils,this.injector(65),this._appEl_65);
    this._Spinner_65_4 = new import87.Spinner(this.parentInjector.get(import62.Config));
    this._appEl_65.initComponent(this._Spinner_65_4,[],compView_65);
    compView_65.create(this._Spinner_65_4,[],null);
    this._text_66 = this.renderer.createText(this._el_63,'\n      ',null);
    this._text_67 = this.renderer.createText(this._el_58,'\n    ',null);
    this._text_68 = this.renderer.createText(this._el_13,'\n    ',null);
    this._el_69 = this.renderer.createElement(this._el_13,'tr',null);
    this._text_70 = this.renderer.createText(this._el_69,'\n      ',null);
    this._el_71 = this.renderer.createElement(this._el_69,'td',null);
    this._text_72 = this.renderer.createText(this._el_71,'crescent',null);
    this._text_73 = this.renderer.createText(this._el_69,'\n      ',null);
    this._el_74 = this.renderer.createElement(this._el_69,'td',null);
    this._text_75 = this.renderer.createText(this._el_74,'\n        ',null);
    this._el_76 = this.renderer.createElement(this._el_74,'ion-spinner',null);
    this.renderer.setElementAttribute(this._el_76,'name','crescent');
    this._appEl_76 = new import79.AppElement(76,74,this,this._el_76);
    var compView_76:any = import96.viewFactory_Spinner0(this.viewUtils,this.injector(76),this._appEl_76);
    this._Spinner_76_4 = new import87.Spinner(this.parentInjector.get(import62.Config));
    this._appEl_76.initComponent(this._Spinner_76_4,[],compView_76);
    compView_76.create(this._Spinner_76_4,[],null);
    this._text_77 = this.renderer.createText(this._el_74,'\n      ',null);
    this._text_78 = this.renderer.createText(this._el_69,'\n    ',null);
    this._text_79 = this.renderer.createText(this._el_13,'\n    ',null);
    this._el_80 = this.renderer.createElement(this._el_13,'tr',null);
    this._text_81 = this.renderer.createText(this._el_80,'\n      ',null);
    this._el_82 = this.renderer.createElement(this._el_80,'td',null);
    this._text_83 = this.renderer.createText(this._el_82,'dots',null);
    this._text_84 = this.renderer.createText(this._el_80,'\n      ',null);
    this._el_85 = this.renderer.createElement(this._el_80,'td',null);
    this._text_86 = this.renderer.createText(this._el_85,'\n        ',null);
    this._el_87 = this.renderer.createElement(this._el_85,'ion-spinner',null);
    this.renderer.setElementAttribute(this._el_87,'name','dots');
    this._appEl_87 = new import79.AppElement(87,85,this,this._el_87);
    var compView_87:any = import96.viewFactory_Spinner0(this.viewUtils,this.injector(87),this._appEl_87);
    this._Spinner_87_4 = new import87.Spinner(this.parentInjector.get(import62.Config));
    this._appEl_87.initComponent(this._Spinner_87_4,[],compView_87);
    compView_87.create(this._Spinner_87_4,[],null);
    this._text_88 = this.renderer.createText(this._el_85,'\n      ',null);
    this._text_89 = this.renderer.createText(this._el_80,'\n    ',null);
    this._text_90 = this.renderer.createText(this._el_13,'\n  ',null);
    this._text_91 = this.renderer.createText(null,'\n\n  ',null);
    this._el_92 = this.renderer.createElement(null,'button',null);
    this._appEl_92 = new import79.AppElement(92,9,this,this._el_92);
    var compView_92:any = import97.viewFactory_Button0(this.viewUtils,this.injector(92),this._appEl_92);
    this._Button_92_4 = new import88.Button(this.parentInjector.get(import62.Config),new import91.ElementRef(this._el_92),this.renderer,null);
    this._appEl_92.initComponent(this._Button_92_4,[],compView_92);
    this._text_93 = this.renderer.createText(null,'Toggle Paused',null);
    compView_92.create(this._Button_92_4,[[].concat([this._text_93])],null);
    this._text_94 = this.renderer.createText(null,'\n\n',null);
    compView_9.create(this._Content_9_4,[
      [].concat([
        this._text_10,
        this._el_11,
        this._text_91,
        this._el_92,
        this._text_94
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_95 = this.renderer.createText(parentRenderNode,'\n',null);
    this._expr_0 = import82.UNINITIALIZED;
    this._expr_1 = import82.UNINITIALIZED;
    this._expr_2 = import82.UNINITIALIZED;
    this._expr_3 = import82.UNINITIALIZED;
    this._expr_4 = import82.UNINITIALIZED;
    this._expr_5 = import82.UNINITIALIZED;
    this._expr_6 = import82.UNINITIALIZED;
    this._expr_7 = import82.UNINITIALIZED;
    this._expr_8 = import82.UNINITIALIZED;
    this._expr_9 = import82.UNINITIALIZED;
    this._expr_10 = import82.UNINITIALIZED;
    this._expr_11 = import82.UNINITIALIZED;
    this._expr_12 = import82.UNINITIALIZED;
    this._expr_13 = import82.UNINITIALIZED;
    this._expr_14 = import82.UNINITIALIZED;
    this._expr_15 = import82.UNINITIALIZED;
    this._expr_16 = import82.UNINITIALIZED;
    this._expr_17 = import82.UNINITIALIZED;
    this._expr_18 = import82.UNINITIALIZED;
    this._expr_19 = import82.UNINITIALIZED;
    this._expr_20 = import82.UNINITIALIZED;
    this._expr_21 = import82.UNINITIALIZED;
    this._expr_22 = import82.UNINITIALIZED;
    this._expr_23 = import82.UNINITIALIZED;
    this._expr_24 = import82.UNINITIALIZED;
    this._expr_25 = import82.UNINITIALIZED;
    this._expr_26 = import82.UNINITIALIZED;
    this._expr_27 = import82.UNINITIALIZED;
    this._expr_28 = import82.UNINITIALIZED;
    this._expr_29 = import82.UNINITIALIZED;
    this._expr_30 = import82.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_92,'click',this.eventHandler(this._handle_click_92_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._text_95
    ]
    ,[disposable_0],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import85.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import84.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Toolbar_2_4; }
    if (((token === import84.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import87.Spinner) && (21 === requestNodeIndex))) { return this._Spinner_21_4; }
    if (((token === import87.Spinner) && (32 === requestNodeIndex))) { return this._Spinner_32_4; }
    if (((token === import87.Spinner) && (43 === requestNodeIndex))) { return this._Spinner_43_4; }
    if (((token === import87.Spinner) && (54 === requestNodeIndex))) { return this._Spinner_54_4; }
    if (((token === import87.Spinner) && (65 === requestNodeIndex))) { return this._Spinner_65_4; }
    if (((token === import87.Spinner) && (76 === requestNodeIndex))) { return this._Spinner_76_4; }
    if (((token === import87.Spinner) && (87 === requestNodeIndex))) { return this._Spinner_87_4; }
    if (((token === import88.Button) && ((92 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._Button_92_4; }
    if (((token === import86.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    changed = false;
    const currVal_2:any = this.context.paused;
    if (import80.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Spinner_21_4.paused = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_21.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_21_4.ngOnInit(); }
    changed = false;
    const currVal_5:any = 'ios';
    if (import80.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Spinner_32_4.name = currVal_5;
      changed = true;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = '1000';
    if (import80.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Spinner_32_4.duration = currVal_6;
      changed = true;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.paused;
    if (import80.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Spinner_32_4.paused = currVal_7;
      changed = true;
      this._expr_7 = currVal_7;
    }
    if (changed) { this._appEl_32.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_32_4.ngOnInit(); }
    changed = false;
    const currVal_10:any = 'ios-small';
    if (import80.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Spinner_43_4.name = currVal_10;
      changed = true;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = '1000';
    if (import80.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Spinner_43_4.duration = currVal_11;
      changed = true;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.context.paused;
    if (import80.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Spinner_43_4.paused = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    if (changed) { this._appEl_43.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_43_4.ngOnInit(); }
    changed = false;
    const currVal_15:any = 'bubbles';
    if (import80.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Spinner_54_4.name = currVal_15;
      changed = true;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this.context.paused;
    if (import80.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Spinner_54_4.paused = currVal_16;
      changed = true;
      this._expr_16 = currVal_16;
    }
    if (changed) { this._appEl_54.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_54_4.ngOnInit(); }
    changed = false;
    const currVal_19:any = 'circles';
    if (import80.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Spinner_65_4.name = currVal_19;
      changed = true;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this.context.paused;
    if (import80.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._Spinner_65_4.paused = currVal_20;
      changed = true;
      this._expr_20 = currVal_20;
    }
    if (changed) { this._appEl_65.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_65_4.ngOnInit(); }
    changed = false;
    const currVal_23:any = 'crescent';
    if (import80.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._Spinner_76_4.name = currVal_23;
      changed = true;
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this.context.paused;
    if (import80.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._Spinner_76_4.paused = currVal_24;
      changed = true;
      this._expr_24 = currVal_24;
    }
    if (changed) { this._appEl_76.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_76_4.ngOnInit(); }
    changed = false;
    const currVal_27:any = 'dots';
    if (import80.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._Spinner_87_4.name = currVal_27;
      changed = true;
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this.context.paused;
    if (import80.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._Spinner_87_4.paused = currVal_28;
      changed = true;
      this._expr_28 = currVal_28;
    }
    if (changed) { this._appEl_87.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_87_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_92_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_92_4.ngAfterContentInit(); }
      this._Button_92_4.ngAfterContentChecked();
    }
    const currVal_0:any = this._Toolbar_2_4._sbPadding;
    if (import80.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Content_9_4._sbPadding;
    if (import80.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this._Spinner_21_4._applied;
    if (import80.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_21,'className',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._Spinner_21_4.paused;
    if (import80.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_21,'spinner-paused',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_8:any = this._Spinner_32_4._applied;
    if (import80.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_32,'className',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Spinner_32_4.paused;
    if (import80.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_32,'spinner-paused',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._Spinner_43_4._applied;
    if (import80.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementProperty(this._el_43,'className',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._Spinner_43_4.paused;
    if (import80.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_43,'spinner-paused',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_17:any = this._Spinner_54_4._applied;
    if (import80.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementProperty(this._el_54,'className',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._Spinner_54_4.paused;
    if (import80.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_54,'spinner-paused',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_21:any = this._Spinner_65_4._applied;
    if (import80.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementProperty(this._el_65,'className',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._Spinner_65_4.paused;
    if (import80.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_65,'spinner-paused',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_25:any = this._Spinner_76_4._applied;
    if (import80.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementProperty(this._el_76,'className',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._Spinner_76_4.paused;
    if (import80.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_76,'spinner-paused',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_29:any = this._Spinner_87_4._applied;
    if (import80.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementProperty(this._el_87,'className',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._Spinner_87_4.paused;
    if (import80.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_87,'spinner-paused',currVal_30);
      this._expr_30 = currVal_30;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_click_92_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.toggleState()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_E2EPage0(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement):import78.AppView<import1.E2EPage> {
  if ((renderType_E2EPage === null)) { (renderType_E2EPage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/main.html',0,import98.ViewEncapsulation.None,styles_E2EPage,{})); }
  return new _View_E2EPage0(viewUtils,parentInjector,declarationEl);
}
var renderType_E2EApp_Host:import77.RenderComponentType = null;
class _View_E2EApp_Host0 extends import78.AppView<any> {
  _el_0:any;
  private _appEl_0:import79.AppElement;
  _E2EApp_0_4:import1.E2EApp;
  constructor(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement) {
    super(_View_E2EApp_Host0,renderType_E2EApp_Host,import81.ViewType.HOST,viewUtils,parentInjector,declarationEl,import82.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import79.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import79.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EApp_0_4 = new import1.E2EApp();
    this._appEl_0.initComponent(this._E2EApp_0_4,[],compView_0);
    compView_0.create(this._E2EApp_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EApp) && (0 === requestNodeIndex))) { return this._E2EApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EApp_Host0(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement):import78.AppView<any> {
  if ((renderType_E2EApp_Host === null)) { (renderType_E2EApp_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EAppNgFactory:import83.ComponentFactory<import1.E2EApp> = new import83.ComponentFactory<import1.E2EApp>('ng-component',viewFactory_E2EApp_Host0,import1.E2EApp);
const styles_E2EApp:any[] = [];
var renderType_E2EApp:import77.RenderComponentType = null;
class _View_E2EApp0 extends import78.AppView<import1.E2EApp> {
  _el_0:any;
  private _appEl_0:import79.AppElement;
  _Nav_0_4:import99.Nav;
  private _expr_0:any;
  constructor(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement) {
    super(_View_E2EApp0,renderType_E2EApp,import81.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import82.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import79.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',null);
    this._appEl_0 = new import79.AppElement(0,null,this,this._el_0);
    var compView_0:any = import100.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import99.Nav(this.parentInjector.get(import89.ViewController,null),this.parentInjector.get(import101.NavControllerBase,null),this.parentInjector.get(import7.App),this.parentInjector.get(import62.Config),this.parentInjector.get(import31.Keyboard),new import91.ElementRef(this._el_0),this.parentInjector.get(import46.NgZone),this.renderer,this.parentInjector.get(import102.ComponentFactoryResolver),this.parentInjector.get(import26.GestureController),this.parentInjector.get(import40.TransitionController));
    this._appEl_0.initComponent(this._Nav_0_4,[],compView_0);
    compView_0.create(this._Nav_0_4,[],null);
    this._expr_0 = import82.UNINITIALIZED;
    this.init([],[this._el_0],[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import99.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.root;
    if (import80.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_0_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_E2EApp0(viewUtils:import80.ViewUtils,parentInjector:import41.Injector,declarationEl:import79.AppElement):import78.AppView<import1.E2EApp> {
  if ((renderType_E2EApp === null)) { (renderType_E2EApp = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/AppModule.ts class E2EApp - inline template',0,import98.ViewEncapsulation.None,styles_E2EApp,{})); }
  return new _View_E2EApp0(viewUtils,parentInjector,declarationEl);
}