version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/core"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-name: "@playwright/test"
      - dependency-name: "@axe-core/playwright"
      - dependency-name: "@stencil/angular-output-target"
      - dependency-name: "@stencil/core"
      - dependency-name: "@stencil/react-output-target"
      - dependency-name: "@stencil/sass"
      - dependency-name: "@stencil/vue-output-target"
      - dependency-name: "ionicons"
