version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/core"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-name: "@playwright/test"
      - dependency-name: "@axe-core/playwright"
      - dependency-name: "@stencil/core"
