# Javascript Node CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          command: |
            npm i -ci
            # Peer dependencies
            npm i vue vue-router vue-template-compiler

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      # run tests!
      - run: npm test && bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

      # SonarQube download, config and scanning
      - run: echo "Starting SonarQube scan"
      - run: wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
      - run: unzip sonar-scanner-cli-3.2.0.1227-linux.zip
      - run: echo "sonar.host.url=https://sonarcloud.io" > sonar-scanner-3.2.0.1227-linux/conf/sonar-scanner.properties
      - run: echo "sonar.login=$sonarqubekey" >> sonar-project.properties
      - run: echo "sonar.organization=$sonarorg" >> sonar-project.properties 
      - run: sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner
      - run: echo "Scan complete, data sent to sonarcloud"

