name: 'Test React Router E2E'
description: 'Test React Router'
inputs:
  app:
    description: 'The specific test application'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react-router
        path: ./packages/react-router
        filename: ReactRouterBuild.zip
    - name: 🧪 Create Test App
      run: ./build.sh ${{ inputs.app }}
      shell: bash
      working-directory: ./packages/react-router/test
    - name: 🕸️ Install Dependencies
      run: npm install --legacy-peer-deps
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: 📦 Install Playwright Browsers
      run: npx playwright install chromium
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: 🔄 Sync Built Changes
      run: npm run sync
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: 🏗️ Build
      run: npm run build
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: 🧪 Run Cypress Tests
      run: npm run e2e
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: 🎭 Run Playwright Tests
      run: npx playwright test --retries=2
      env:
        CI: true
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
