import 'ionicons';

export { createAnimation } from './utils/animation/animation';
export { iosTransitionAnimation } from './utils/transition/ios.transition';
export { mdTransitionAnimation } from './utils/transition/md.transition';
export { getTimeGivenProgression } from './utils/animation/cubic-bezier';
export { createGesture } from './utils/gesture';
export { initialize } from './global/ionic-global';
export { componentOnReady } from './utils/helpers';
export { isPlatform, Platforms, PlatformConfig, getPlatforms } from './utils/platform';
export { IonicSafeString } from './utils/sanitization';
export { IonicConfig, getMode, setupConfig } from './utils/config';
export { LIFECYCLE_WILL_ENTER, LIFECYCLE_DID_ENTER, LIFECYCLE_WILL_LEAVE, LIFECYCLE_DID_LEAVE, LIFECYCLE_WILL_UNLOAD } from './components/nav/constants';
export { menuController } from './utils/menu-controller';
export { alertController } from './components/alert/alert-controller';
export { actionSheetController } from './components/action-sheet/action-sheet-controller';
export { modalController } from './components/modal/modal-controller';
export { loadingController } from './components/loading/loading-controller';
export { pickerController } from './components/picker/picker-controller';
export { popoverController } from './components/popover/popover-controller';
export { toastController } from './components/toast/toast-controller';
export { IonicSwiper } from './components/slides/IonicSwiper';
