/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import 'ionicons';


import {
  Page as IonPage
} from './components/page/page';

declare global {
  interface HTMLIonPageElement extends IonPage, HTMLElement {
  }
  var HTMLIonPageElement: {
    prototype: HTMLIonPageElement;
    new (): HTMLIonPageElement;
  };
  interface HTMLElementTagNameMap {
    "ion-page": HTMLIonPageElement;
  }
  interface ElementTagNameMap {
    "ion-page": HTMLIonPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ion-page": JSXElements.IonPageAttributes;
    }
  }
  namespace JSXElements {
    export interface IonPageAttributes extends HTMLAttributes {
      
    }
  }
}

