name: 🐛 Bug Report
description: Create a report to help us improve Ionic Framework
title: 'bug: '

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
          required: true
        - label: I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
          required: true
        - label: I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.
          required: true

  - type: dropdown
    id: affected-versions
    attributes:
      label: Ionic Framework Version
      description: Which version(s) of Ionic Framework does this issue impact? [Ionic Framework 1.x to 6.x are no longer supported](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status). For extended support, considering visiting [Ionic's Enterprise offering](https://ionic.io/enterprise).
      options:
        - v7.x
        - v8.x (Beta)
        - Nightly
      multiple: true
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Explain the steps required to reproduce this issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe: '...'
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Code Reproduction URL
      description: |
        Reproduce this issue in a blank [Ionic Framework starter application](https://ionicframework.com/start#basics) or a Stackblitz example.

        You can use the Stackblitz button available on any of the component docs pages to open an editable example. Remember to save your changes to obtain a link to copy.

        Reproductions cases must be minimal and focused around the specific problem you are experiencing. This is the best way to ensure this issue is triaged quickly. Issues without a code reproduction may be closed if the Ionic Team cannot reproduce the issue you are reporting.
      placeholder: https://github.com/...
    validations:
      required: true

  - type: textarea
    id: ionic-info
    attributes:
      label: Ionic Info
      description: Please run `ionic info` from within your Ionic Framework project directory and paste the output below.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.
