/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  PageOne as PageOne
} from './components/page-one/page-one';

declare global {
  interface HTMLPageOneElement extends PageOne, HTMLStencilElement {
  }
  var HTMLPageOneElement: {
    prototype: HTMLPageOneElement;
    new (): HTMLPageOneElement;
  };
  interface HTMLElementTagNameMap {
    "page-one": HTMLPageOneElement;
  }
  interface ElementTagNameMap {
    "page-one": HTMLPageOneElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "page-one": JSXElements.PageOneAttributes;
    }
  }
  namespace JSXElements {
    export interface PageOneAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  PageTwo as PageTwo
} from './components/page-two/page-two';

declare global {
  interface HTMLPageTwoElement extends PageTwo, HTMLStencilElement {
  }
  var HTMLPageTwoElement: {
    prototype: HTMLPageTwoElement;
    new (): HTMLPageTwoElement;
  };
  interface HTMLElementTagNameMap {
    "page-two": HTMLPageTwoElement;
  }
  interface ElementTagNameMap {
    "page-two": HTMLPageTwoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "page-two": JSXElements.PageTwoAttributes;
    }
  }
  namespace JSXElements {
    export interface PageTwoAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  TabOne as TabOne
} from './components/tab-one/tab-one';

declare global {
  interface HTMLTabOneElement extends TabOne, HTMLStencilElement {
  }
  var HTMLTabOneElement: {
    prototype: HTMLTabOneElement;
    new (): HTMLTabOneElement;
  };
  interface HTMLElementTagNameMap {
    "tab-one": HTMLTabOneElement;
  }
  interface ElementTagNameMap {
    "tab-one": HTMLTabOneElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "tab-one": JSXElements.TabOneAttributes;
    }
  }
  namespace JSXElements {
    export interface TabOneAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  TabThree as TabThree
} from './components/tab-three/tab-three';

declare global {
  interface HTMLTabThreeElement extends TabThree, HTMLStencilElement {
  }
  var HTMLTabThreeElement: {
    prototype: HTMLTabThreeElement;
    new (): HTMLTabThreeElement;
  };
  interface HTMLElementTagNameMap {
    "tab-three": HTMLTabThreeElement;
  }
  interface ElementTagNameMap {
    "tab-three": HTMLTabThreeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "tab-three": JSXElements.TabThreeAttributes;
    }
  }
  namespace JSXElements {
    export interface TabThreeAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  TabTwo as TabTwo
} from './components/tab-two/tab-two';

declare global {
  interface HTMLTabTwoElement extends TabTwo, HTMLStencilElement {
  }
  var HTMLTabTwoElement: {
    prototype: HTMLTabTwoElement;
    new (): HTMLTabTwoElement;
  };
  interface HTMLElementTagNameMap {
    "tab-two": HTMLTabTwoElement;
  }
  interface ElementTagNameMap {
    "tab-two": HTMLTabTwoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "tab-two": JSXElements.TabTwoAttributes;
    }
  }
  namespace JSXElements {
    export interface TabTwoAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
