name: 'Build Ionic Core with Stencil Prerelease'
description: 'Build Ionic Core with a Prerelease Build of Stencil'
inputs:
  stencil-core-version:
    description: 'The NPM tag of @stencil/core to install.'
    type: string
    required: true
  stencil-react-output-target-version:
    description: 'The NPM tag of @stencil/react-output-target to install.'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24.x

    - name: 🕸️ Install Dependencies
      run: npm ci
      working-directory: ./core
      shell: bash
    - name: 📦 Install Stencil Core ${{ inputs.stencil-core-version }}
      working-directory: ./core
      run: npm i @stencil/core@${{ inputs.stencil-core-version }}
      shell: bash
    - name: 📦 Install Stencil React Output Target ${{ inputs.stencil-react-output-target-version }}
      working-directory: ./core
      run: npm i @stencil/react-output-target@${{ inputs.stencil-react-output-target-version }}
      shell: bash
    - name: 🏗️ Build Core
      run: npm run build -- --ci --debug --verbose
      working-directory: ./core
      shell: bash
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-core
        output: core/CoreBuild.zip
        paths: core/dist core/components core/css core/hydrate core/loader core/src/components.d.ts core/package.json packages/react/src/components/components.ts
