name: 'Ionic Framework Archive Upload'
description: 'Compresses and uploads an archive to be reused across jobs'
inputs:
  paths:
    description: 'Paths to files or directories to archive'
  output:
    description: 'Output file name'
  name:
    description: 'Archive name'
runs:
  using: 'composite'
  steps:
    - name: 🗄️ Create Archive
      run: zip -q -r ${{ inputs.output }} ${{ inputs.paths }}
      shell: bash
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.output }}
