export * from './plugin'
export * from './battery/battery'
export * from './camera/camera'
export * from './contacts/contacts'
export * from './device/device'
export * from './device-motion/device-motion'
export * from './geolocation/geolocation'
export * from './vibration/vibration'
