// DON'T reference this file in the source. Only in demos.
export * from 'ionic2/components/action-menu/action-menu'
export * from 'ionic2/components/alert/alert'
export * from 'ionic2/components/aside/aside'
export * from 'ionic2/components/button/button'
export * from 'ionic2/components/checkbox/checkbox'
export * from 'ionic2/components/content/content'
export * from 'ionic2/components/icon/icon'
export * from 'ionic2/components/item/item'
export * from 'ionic2/components/list/list'
export * from 'ionic2/components/nav-view/nav-view'
export * from 'ionic2/components/nav-viewport/nav-viewport'
export * from 'ionic2/components/tabs/tabs'
export * from 'ionic2/components/tabs/tab'
export * from 'ionic2/components/toolbar/toolbar'
export * from 'ionic2/components/view/view'
