name: Assign issues to triage

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@af6beea6bdf1e8eb373f061c5bc168681fc6d011 # v4.0.1
        with:
          assignees: brandyscarney, thetaPC, ShaneK
          numOfAssignee: 1
          allowSelfAssign: false
