name: Assign issues to triage

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@70adb98ca8b3941524e9ecde48e89067c4f96736 # v3.0.0
        with:
          assignees: brandyscarney, thetaPC, ShaneK
          numOfAssignee: 1
          allowSelfAssign: false
