name: 'Deploy Preview'
description: 'Deploys the HTML test files to a public bucket for preview'

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
  push:
    branches:
      - 'next'

# When pushing a new commit we should
# cancel the previous test run to not
# consume more runners than we need to.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/build-core
