name: 'Ionic Framework Archive Download'
description: 'Downloads and decompresses an archive from a previous job'
inputs:
  path:
    description: 'Input archive name'
  filename:
    description: 'Input file name'
  name:
    description: 'Archive name'
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
    - name: 🔎 Extract Archive
      run: unzip -q -o ${{ inputs.path }}/${{ inputs.filename }}
      shell: bash
